dist: bionic
sudo: required
language: cpp

addons:
  apt:
    update: true
    source:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - clang-10

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=Ts
  - BUILD_TYPE=address

script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi
  - cd graph_cases
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B. -S.. ..
  - make
  - tests/tests
